spring:
  application:
    name: hypermedicus

  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/malldb?characterEncoding=UTF-8
      driver-class-name: org.mariadb.jdbc.Driver
      username: malldbuser
      password: malldbuser

  #datasource:
  #  hikari:
  #    jdbc-url: jdbc:postgresql://localhost:5432/postgres
  #    driver-class-name: org.postgresql.Driver
  #    username: postgres
  #    password: synergy